# Generated by Django 5.1.7 on 2025-03-21 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Restaurante', '0002_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
