# Generated by Django 5.1.7 on 2025-03-21 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Restaurante', '0003_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Listo', 'Listo')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web_Restaurante.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web_Restaurante.menu')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web_Restaurante.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='platillos',
            field=models.ManyToManyField(through='Web_Restaurante.OrderDetail', to='Web_Restaurante.menu'),
        ),
    ]
