# Generated by Django 5.1.7 on 2025-03-23 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Restaurante', '0004_order_orderdetail_order_platillos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='fecha_creacion',
            new_name='fecha_registro',
        ),
    ]
