# Generated by Django 5.1.7 on 2025-03-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Restaurante', '0005_rename_fecha_creacion_order_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Listo', 'Listo'), ('Cancelado', 'Cancelado')], max_length=20),
        ),
    ]
