# Generated by Django 5.2.7 on 2025-11-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Restaurante', '0006_alter_order_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(default='Sistema de Restaurante ADM', max_length=200, verbose_name='Nombre del Restaurante')),
                ('restaurant_address', models.CharField(blank=True, max_length=300, verbose_name='Dirección')),
                ('restaurant_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('restaurant_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('itbis_rate', models.DecimalField(decimal_places=2, default=18.0, help_text='Ingrese el porcentaje sin el símbolo %. Ejemplo: 18.00 para 18%', max_digits=5, verbose_name='Tasa de ITBIS (%)')),
                ('invoice_footer_message', models.TextField(default='Gracias por su preferencia', help_text='Mensaje que aparecerá al final de las facturas', verbose_name='Mensaje de pie de página')),
                ('suggested_tip_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Porcentaje de propina sugerida. Ejemplo: 10.00 para 10%', max_digits=5, verbose_name='Propina sugerida (%)')),
                ('show_tip_in_invoice', models.BooleanField(default=False, verbose_name='Mostrar propina en factura')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
            },
        ),
    ]
