# Generated by Django 5.2.7 on 2025-11-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Restaurante', '0007_systemconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Listo', 'Listo'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], max_length=20),
        ),
    ]
